### ISSUE TITLE
🎯 What can I help with ? (api-documentation)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/api-documentation#23]
#### Fix bugs
- [x] openfoodfacts/api-documentation#4 

#### Simplify, clarify and fix the existing documentation

- [ ] Fix the image upload explanations

#### Document new APIs

- [ ] openfoodfacts/api-documentation#5 
- [x] openfoodfacts/api-documentation#14 
- [x] openfoodfacts/api-documentation#15 
- [ ] openfoodfacts/openfoodfacts-server#10180 
- [ ] openfoodfacts/api-documentation#17 
- [ ] openfoodfacts/openfoodfacts-server#10183 
- [x] openfoodfacts/api-documentation#19 
- [x] openfoodfacts/api-documentation#9 
- [ ] openfoodfacts/api-documentation#10 
- [ ] openfoodfacts/openfoodfacts-server#10187 
- [ ] openfoodfacts/api-documentation#71 
- [ ] openfoodfacts/api-documentation#70 
- [x] openfoodfacts/api-documentation#68 
- [ ] openfoodfacts/api-documentation#66 
- [ ] openfoodfacts/api-documentation#62 
- [ ] openfoodfacts/api-documentation#61 
- [x] openfoodfacts/api-documentation#49
- [ ] openfoodfacts/api-documentation#37
#### Create API use cases
- [x] openfoodfacts/api-documentation#6 
- [x] openfoodfacts/api-documentation#21 
#### Document and valorize the SDKs within the doc
- [ ] openfoodfacts/openfoodfacts-server#10179 

#### Disseminate the doc
- [x] openfoodfacts/api-documentation#8 

### To be sorted
- [x] openfoodfacts/openfoodfacts-server#10184 
- [ ] openfoodfacts/api-documentation#12 
- [ ] openfoodfacts/api-documentation#13 
- [ ] openfoodfacts/api-documentation#20 
- [ ] openfoodfacts/api-documentation#22 

### Done
- [ ] openfoodfacts/api-documentation#1 
- [ ] openfoodfacts/api-documentation#2 
- [ ] openfoodfacts/api-documentation#3

### Why

- The better the documentation, the easier it is to use the API, the better Open Food Facts can fulfill its mission

**Comment by Dule-martins** [comment]
Hey 👋

I'm interested in working on the Open Food Fact project for the Google Season of Docs.
What do you advise, I do?

**Comment by BeeC00des** [comment]
Hi,
I will love to contribute to this project. 
How do I get started?

**Comment by teolemon** [comment]
Sorry for the delay @OmoBolarinwaye @Dule-mart, are you already on Slack ? (https://slack.openfoodfacts.org)
I've also created a form to manifest your interest: https://forms.gle/8ME8RoGDVUw3r8cK9

If you're interested, you can pick any issue above to get familiar with the current tooling (we're also open to suggestions for alternative Open-API compliant tooling, btw)

**Comment by hhaider00** [comment]
Hello, I would like to contribute to this project, is that possible?

**Comment by Dule-martins** [comment]
Hey! Is this still valid?
